version: 2
# 依存関係更新の思想：
# 1. セキュリティとメンテナンス性の両立
#   - パッチ更新は安全性が高いため、週次でまとめて自動更新
#   - マイナー更新は機能追加が主のため、月1回のペースで計画的に更新
#   - メジャー更新は破壊的変更を含むため、個別に慎重にレビュー
# 2. 開発効率の最適化
#   - パッチとマイナーはまとめてPR化することで、レビュー工数を削減
#   - メジャー更新は個別PRとすることで、影響範囲を明確に把握
# 3. 更新タイミングの戦略的選択
#   - パッチ更新は月曜に設定し、週初めのタイミングで対応
#   - メジャー更新は金曜に設定し、週末のリスクを最小化
#   - マイナー更新は月初め（毎月の最初の月曜日）に設定し、月間の計画に組み込み
# 4. グループ化戦略
#   - UI関連ライブラリ（Tailwind, Radix UI等）を一つのグループに
#   - Next.js/React関連を一つのグループに
#   - その他のライブラリを別グループに
#   これにより、関連する変更を一括でレビュー可能に
#
# dependabotによるライブラリ更新戦略
# patchリリース：毎週月曜日に3グループ（UI/Next.js/その他）に分けてPRを作成
# minorリリース：毎月1回、同様の3グループに分けてPRを作成
# majorリリース：毎週金曜日に個別PRを作成
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # 月に一度、最初の月曜日の 05:00 (UTC) に実行
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
    version-requirement-updates: "increase"
    versioning-strategy: "auto"

    # --- グループ定義 ---
    groups:
      # 1) Patch 用グループ

      ui-libraries-patch:
        patterns:
          - "class-variance-authority"
          - "clsx"
          - "lucide-react"
          - "^@radix-ui/.*" # Radix
          - "tailwind-merge"
          - "tailwindcss"
          - "tailwindcss-animate"
        update-types:
          - patch

      next-react-libraries-patch:
        patterns:
          - "^react$"
          - "^react-dom$"
          - "^@types/react"
          - "^@types/react-dom"
          - "^next$"
          - "^@cloudflare/next-on-pages"
          - "^vercel$"
        update-types:
          - patch

      cloudflare-libraries-patch:
        patterns:
          - "^@cloudflare$"
        update-types:
          - patch

      other-libraries-patch:
        # 上記に当てはまらないパッケージのパッチ更新
        patterns:
          - "*"
        update-types:
          - patch

      # 2) Minor 用グループ

      ui-libraries-minor:
        patterns:
          - "class-variance-authority"
          - "clsx"
          - "lucide-react"
          - "^@radix-ui/.*"
          - "tailwind-merge"
          - "tailwindcss"
          - "tailwindcss-animate"
        update-types:
          - minor

      next-react-libraries-minor:
        patterns:
          - "^react$"
          - "^react-dom$"
          - "^@types/react"
          - "^@types/react-dom"
          - "^next$"
          - "^@cloudflare/next-on-pages"
          - "^vercel$"
        update-types:
          - minor

      cloudflare-libraries-minor:
        patterns:
          - "^@cloudflare$"
        update-types:
          - minor

      other-libraries-minor:
        patterns:
          - "*"
        update-types:
          - minor

      # 3) Major はグルーピングしない → 個別 PR
      #    (定義しなければ個別 PR になる)
