import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "My New App",
	description: "Generated by Onlook",
	robots: {
		index: false,
		follow: false,
	},
};

export const runtime = "edge";

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" data-oid="ad3d_3-">
			<body className={inter.className} data-oid="wnaywc8">
				{children}
			</body>
		</html>
	);
}
