name: Lighthouse CI
# TODO: リリース後、適切なスコアをクリアしなければ失敗するようにする
# 実行タイミングは日本時間の毎日午前6時
on:
  schedule:
    - cron: '0 21 * * *'
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://ryosuke-horie-work.pages.dev/
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage