name: Lint(Biome)

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install

            - name: Lint with Biome
              run: npm run lint
